### ISSUE TITLE
First milestone todo list

### ISSUE THREAD

**Issue by Admer456** [ElegyEngine/ElegyEngine#1]
### Asset loading
* [x] Asset loader plugin interfaces (model loaders, texture loaders etc.)
* [x] GLTF loading
* [ ] OBJ loading

### Console system
* [x] Coloured text
* [x] ~~Move `GodotConsoleFrontend` into its own module~~
* [ ] File logger
* [ ] Console variables
* [x] Console commands
* [ ] Autocompletion facilities

### DevConsoleApp
* [x] Maintain connection
* [x] Display messages
* [x] Run the bridge on a separate thread
* [ ] Autocomplete
* [x] Execute commands

### Map compiler
* [x] Parse map geometry
* [x] Write in a custom map format
* [ ] Spatial partitioning

### Material system
* [x] Material assets
* [x] Parsing the materials

### Model manager
* [x] Model data structures
* [x] Creating meshes

### Plugin system
* [ ] Handle cases where plugins have their own dependencies (search paths for plugins)

### Game SDK
This one will be talked about in another repository, and there will be a lot of stuff to solve. The entity system, main menu, player interaction and networking are just some of the topics.

### Core
~~Investigate upgrading to the latest Godot 4 version. It appears as though beta 17 introduced some regressions, so we'll wait for beta 18 or 19, or the RC.~~ It's on 4.0 stable now.

~~Also look into separating `Elegy.Engine` into two libraries: the engine (`Elegy.Engine`) + the utility library (`Elegy.Common`).~~ The engine is now split up.

Once this is all done, we can begin some testing to get an idea of what works and what doesn't.

**Comment by Admer456** [comment]
Pausing development until 20th of March 2023. Reason: exams and personal projects that were in the backlog for a year.

**Comment by Admer456** [comment]
Upgraded to Godot 4 stable. The test game runs fine.

**Comment by Admer456** [comment]
`DevConsole` now runs on a separate thread, so it can maintain a constant connection. Loading in the game module is still on the main thread, so messages only get sent *after* the game has fully loaded. `IByteBuffer` and others have been added to make writing to/reading from binary blobs a lot easier, however it's still missing reads/writes for `Vector3` and others.

Next in line is probably executing console commands (this involves con. variables and autocomplete), and then a map compiler perhaps. And that'll be it for March.

April should be about asset importing etc., May and onward about the game SDK, so I hope to reach a little dev preview in August this year.

**Comment by Admer456** [comment]
I moved `Elegy.TestGame`'s map loading code to `Elegy.MapCompiler`, although the changes aren't public yet. Soon we'll be able to compile maps with a standalone tool.

After milestone 0.1, I will need to reconsider the architecture of the engine, because the map compiler tool really needs to use the engine's subsystems (`FileSystem` mainly, but without doubt it'll use `MaterialSystem` and `RenderSystem` when those are a thing).

The map compiler will most likely be an engine plugin in the end.

**Comment by Admer456** [comment]
`Elegy.MapCompiler`, EMC for short, is public now. The work for April will involve:
* [ ] EMC: octree subdivision
* [ ] EMC: smooth normals
* [ ] `IModelLoader` plugin interface, so we can load various model formats without relying on Godot
  * This also means we'll need to come up with an internal model format.
* [ ] Game: load map files compiled by EMC
  * Map document classes are currently in EMC, so they'll need to be moved into `Elegy.Common`.
* [ ] Console variables
* [ ] Console commands

**Comment by Admer456** [comment]
A draft for generic N-dimensional spatial trees is done. We'll have octree subdivision & ELF loading as soon as next week.

**Comment by Admer456** [comment]
In the past few months I've decided that double-grid partitioning is better than octree partitioning for my usecases. It is simpler to work with, I can make better use of it than an octree, and it's hilariously fast for radius searches.

I don't have time to work on this this month, so I'm moving the April workload to October. The todo list still applies.

**Comment by Admer456** [comment]
The game loads maps compiled by EMC now, and console commands & variables are en route.

**Comment by Admer456** [comment]
Console commands are almost there, and `Elegy.DevConsoleApp` can now send console command packets!
My free time is slowly increasing so I will be able to finish some more stuff throughout Q1 2024.

**Comment by Admer456** [comment]
Continues in #3
