### ISSUE TITLE
First milestone todo list v2

### ISSUE THREAD

**Issue by Admer456** [ElegyEngine/ElegyEngine#3]
The old todo list (#1) was when Elegy was still on Godot. In January/February, the engine split off from Godot to have its own backends.

So here's the new one:
### Asset system
* [ ] OBJ loading
* [ ] PNG loading

### Console system
* [ ] File logger
* [ ] Console variables
* [ ] Autocompletion facilities for console commands

### DevConsoleApp
* [ ] Rewrite in C# with [spectre.console](https://github.com/spectreconsole/spectre.console)
  * [ ] Displaying messages
  * [ ] Sending console commands
  * [ ] Completion suggestions
  * [ ] Autocomplete

### Map compiler
* [ ] Use engine's FileSystem etc.
* [ ] Spatial partitioning
  * [ ] Implement `Grid` spatial collection in Elegy.Common
* [ ] Smooth normals
* [ ] Use GLTF as the base format for levels

### Plugin system
* [ ] Handle plugins' own dependencies

### Tests
* [ ] Geometry:
  * [ ] Polygon3 and Polygon3D
* [ ] Maths:
  * [ ] Box3
  * [ ] Rect2 and Rect2I
  * [ ] Utils
* [ ] Reflection:
  * [ ] TypeInfo
* [ ] SpatialCollections:
  * [ ] Octree
  * [ ] Quadtree
* [ ] Text:
  * [ ] Lexer
* [ ] Utilities:
  * [ ] ByteBuffer
  * [ ] ByteBufferDynamic
  * [ ] Parse

## Game SDK
The game SDK will be talked about in another issue, and there will be a lot of stuff to solve. The entity system, main menu and networking are just some of the topics.
